name: Docker Workflow
on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  build_Docker_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: Clean
        run: mvn -ntp clean
      - name: Build
        run: mvn -ntp compile
      - name: Short tests
        run: mvn -ntp test -Dtest='CalculatorTest'
      - name: Long tests
        run: mvn -ntp test -Dtest='CalculatorTestThorough'

      - name: Package
        run: mvn -ntp package

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: jzachary0114/github-actions-calculator

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#testing secrets new day
